# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 204860b38e95707e496416121297b2d8acc01e58e334d9f04cf4086dae23dc430a01f390cae4ff554e6690e0fe4120c03a06dde3762329a62002e964be5db0cf

test:
  secret_key_base: 91f332f577fa82c3e0c5dcb72688899bb1fc7b4dabec4b0750def640ed380dbccac357017f26f135b0f20146282f660af906a9a9ea01161446088fdf0535c1bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
